import '../../../l10n/app_localizations.dart';

/// 课程域页面文案与纯格式化工具。
///
/// 课程域 l10n 键(在 `lib/l10n/*.arb`)只覆盖目录/详情的主要标题;AI 总结、
/// 筛选、写评表单、相关课程与沿革等细粒度文案对齐 web
/// (`resource/src/locales/zh.ts|en.ts` 的 courseSummary/courseDetailPage/
/// coursesPage),此处以 zh/en 双份内联镜像,待 arb 放开后可收敛。
class CourseCopy {
  CourseCopy(this.l10n);

  final AppLocalizations l10n;

  bool get _zh => l10n.localeName == 'zh';

  String _t(String zh, String en) => _zh ? zh : en;

  // ---- 目录 ----
  String get creditUnit => _t('学分', 'Credits');
  String get noTeacher => _t('无教师', 'No teacher');
  String get catalogEmptyTitle => _t('暂无课程', 'No courses yet');
  String get catalogEmptyDescription =>
      _t('课程目录尚未导入。', 'The course catalog has not been imported yet.');
  String get noFilterResults =>
      _t('没有找到符合筛选条件的课程。', 'No courses match these filters.');
  String get noFilterResultsDescription => _t(
    '试试调整或清除筛选，查看更广的课程。',
    'Try adjusting or clearing filters to see more courses.',
  );
  String get clearSearch => _t('清空搜索', 'Clear search');
  String get done => _t('完成', 'Done');
  String get noOptions => _t('暂无可选项', 'No options available');
  String selectedCount(int count) => _t('已选 $count 项', '$count selected');
  String get instructorInputHint =>
      _t('输入教师姓名，回车添加', 'Enter an instructor name and press enter');
  String get instructorAdd => _t('添加', 'Add');
  String get instructorEmptyHint =>
      _t('通过上方输入框添加教师', 'Add instructors with the field above');

  // ---- 详情头部 ----
  String get aliasesLabel => _t('别名：', 'Aliases: ');
  String get legacyNamesLabel => _t('原名：', 'Former name: ');
  String get reviewScopeTeam => _t('教学团队', 'Teaching Team');
  String get reviewScopeCourse => _t('课程级评价', 'Course-level Reviews');
  String get teamInstructorsPrefix => _t('教学团队 · ', 'Teaching team · ');
  String teamInstructorsSuffix(int count) =>
      _t('等 $count 位教师', ' ($count teachers)');

  // ---- 评分卡 ----
  String get ratingTitle => _t('课程评分', 'Course rating');
  String get ratingOutOf => _t('/ 5.0', '/ 5.0');
  String get noRatingQuiet => _t('暂无评分', 'No rating yet');

  // ---- 开课班级 / 聚焦 ----
  String get offeringsEmpty => _t('暂无开课记录。', 'No offerings yet.');
  String get offeringFocusLabel =>
      _t('只看该教学班的评价', 'Showing reviews for this class only');
  String get offeringFocusClear => _t('查看全部评价', 'Show all reviews');

  // ---- AI 总结 ----
  String get summaryGenerated => _t('已生成', 'Generated');
  String get summaryKeywords => _t('关键词', 'Keywords');
  String get summaryPros => _t('优点', 'Pros');
  String get summaryCons => _t('缺点', 'Cons');
  String get summaryRepresentativeReviews =>
      _t('代表性评价', 'Representative reviews');
  String get summarySentimentPositive => _t('好评', 'Positive');
  String get summarySentimentNeutral => _t('中立', 'Neutral');
  String get summarySentimentNegative => _t('差评', 'Negative');
  String get summaryRefresh => _t('刷新', 'Refresh');
  String get summaryExpand => _t('展开', 'Expand');
  String get summaryCollapse => _t('收起', 'Collapse');
  String get summaryDisclaimer => _t(
    '以上内容由 AI 基于学生评价自动生成，仅供参考，不构成选课建议。',
    'Generated by AI from student reviews. For reference only; not a course recommendation.',
  );
  String get summaryInsufficient => _t(
    '评价数量不足，暂无法生成 AI 总结。',
    'Not enough reviews to generate an AI summary yet.',
  );
  String get summaryLoadFailed => _t(
    'AI 总结生成失败，请稍后重试。',
    'Failed to generate the AI summary. Please try again later.',
  );

  String summaryConsensus(String level) {
    const Map<String, String> zh = {
      'strong_recommend': '强烈推荐',
      'recommend': '推荐',
      'neutral': '褒贬不一',
      'cautious': '谨慎选择',
      'not_recommend': '不推荐',
    };
    const Map<String, String> en = {
      'strong_recommend': 'Strongly recommended',
      'recommend': 'Recommended',
      'neutral': 'Mixed',
      'cautious': 'Caution advised',
      'not_recommend': 'Not recommended',
    };
    final Map<String, String> table = _zh ? zh : en;
    return table[level] ?? level;
  }

  String summaryConsensusText(String level) {
    const Map<String, String> zh = {
      'strong_recommend': '多数同学强烈推荐这门课程。',
      'recommend': '多数同学推荐这门课程。',
      'neutral': '同学们对这门课程的评价褒贬不一。',
      'cautious': '多数同学建议谨慎选择这门课程。',
      'not_recommend': '多数同学不推荐这门课程。',
    };
    const Map<String, String> en = {
      'strong_recommend': 'Most students strongly recommend this course.',
      'recommend': 'Most students recommend this course.',
      'neutral': 'Students have mixed opinions about this course.',
      'cautious': 'Most students advise caution before choosing this course.',
      'not_recommend': 'Most students do not recommend this course.',
    };
    final Map<String, String> table = _zh ? zh : en;
    return table[level] ?? level;
  }

  String summarySentiment(String sentiment) => switch (sentiment) {
    'positive' => summarySentimentPositive,
    'negative' => summarySentimentNegative,
    _ => summarySentimentNeutral,
  };

  // ---- 写评 / 课评操作 ----
  String get writeReviewTitle => _t('写一条评价', 'Write a review');
  String get editReviewTitle => _t('编辑评价', 'Edit review');
  String get selectOffering => _t('选择开课实例', 'Select offering');
  String get ratingLabel => _t('评分', 'Rating');
  String get contentLabel => _t('评价内容', 'Review');
  String get contentPlaceholder => _t(
    '写下你的学习体验、课程质量或给分情况…',
    'Share your experience with the course, teaching quality, or grading…',
  );
  String get ratingRequired =>
      _t('请选择 1–5 星评分。', 'Please choose a 1–5 star rating.');
  String get contentRequired =>
      _t('评价内容不能为空。', 'Review content cannot be empty.');
  String get anonymousLabel =>
      _t('匿名发布（对公众隐藏身份）', 'Post anonymously (identity hidden from the public)');
  String get submitSuccess => _t('已提交', 'Submitted');
  String get updateSuccess => _t('已更新', 'Updated');
  String get delete => _t('删除', 'Delete');
  String get deleteReviewTitle => _t('删除评价', 'Delete review');
  String get confirmDeleteReview =>
      _t('确定删除这条评价吗？删除后不可恢复。', 'Delete this review? This cannot be undone.');
  String get reviewDeleted => _t('评价已删除', 'Review deleted');
  String get operationFailed =>
      _t('操作失败，请稍后重试。', 'Operation failed. Please try again later.');
  String get reviewsLoadFailed =>
      _t('评价加载失败，请稍后重试。', 'Failed to load reviews. Please try again later.');
  String get authorAnonymousLabel => _t('匿名同学', 'Anonymous');
  String get authorLegacyLabel => _t('历史匿名评价', 'Legacy anonymous review');

  // ---- 相关课程 / 沿革 ----
  String get relatedTeacherCoursesTitle =>
      _t('同教师其他课程', 'Other courses by the same teachers');
  String get relatedOtherTeachersTitle =>
      _t('同课程其他教师', 'Other teachers of this course');
  String get relatedEmpty => _t('暂无相关内容', 'No related content');
  String get relationEquivalent => _t('等价', 'Equivalent');
  String get relationRenamed => _t('改名', 'Renamed');
  String get relationSplit => _t('拆分', 'Split');
  String get relationMerged => _t('合并', 'Merged');
  String get relationRelated => _t('相关', 'Related');
  String relationLabel(String type) => switch (type) {
    'EQUIVALENT' => relationEquivalent,
    'RENAMED_FROM' => relationRenamed,
    'SPLIT_FROM' => relationSplit,
    'MERGED_FROM' => relationMerged,
    'RELATED' => relationRelated,
    _ => type,
  };
}

/// 学期代码缩写（对齐 web `shortTerm`）：`2025-2026-2` → `25春`；
/// 1=秋、2=春；非标准码原样返回。
String shortTerm(String term) {
  final RegExpMatch? m = RegExp(
    r'^(\d{4})-(\d{4})-([12])$',
  ).firstMatch(term.trim());
  if (m == null) return term;
  return '${m.group(1)!.substring(2)}${m.group(3) == '1' ? '秋' : '春'}';
}

/// 学期排序键：标准码按 startYear*10+semester；非标准码 -1。
int termSortKey(String term) {
  final RegExpMatch? m = RegExp(
    r'^(\d{4})-(\d{4})-([12])$',
  ).firstMatch(term.trim());
  return m == null ? -1 : int.parse(m.group(1)!) * 10 + int.parse(m.group(3)!);
}

/// 最近学期按时间降序（最新在前），非标准码（如「其他」）恒置末尾。
List<String> sortedRecentTerms(List<String>? terms) {
  final List<String> list = [...?terms];
  list.sort((a, b) {
    final int ka = termSortKey(a);
    final int kb = termSortKey(b);
    if (ka < 0 && kb < 0) return 0;
    if (ka < 0) return 1;
    if (kb < 0) return -1;
    return kb - ka;
  });
  return list;
}

/// 学分展示（对齐 web `formatCredit`）：25 → 2.5，50 → 5（去掉 `.0`）。
String formatCreditText(int creditX10) {
  if (creditX10 <= 0) return '';
  final String value = (creditX10 / 10).toStringAsFixed(1);
  return value.replaceFirst(RegExp(r'\.0$'), '');
}

/// 均分展示：恒一位小数（4 → 4.0，对齐 web ratingAvg.toFixed(1)）。
String formatRating(double? ratingAvg) {
  if (ratingAvg == null || ratingAvg <= 0) return '—';
  return ratingAvg.toStringAsFixed(1);
}
